### ISSUE TITLE
No way to specify custom paths for loading translations

### ISSUE THREAD

**Issue by aidenwallis** [larscom/ngx-translate-module-loader#1]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, paths are built automatically built with the `${baseTranslateUrl}/${moduleName}/${language}${fileType}` etc.

## Expected behavior

Would be nice if we could change this variable, in the case our translations are structured differently (for example, mine are, for example `en/home.json`).

## What is the motivation / use case for changing the behavior?

Adds more flexibility for anyone wanting to write translations, and different people have different file structures so would be nice to be able to change this.

Others:
I'll submit a PR doing this for you 👍

**Comment by aidenwallis** [comment]
https://github.com/larscom/ngx-translate-module-loader/pull/2 👍

**Comment by larscom** [comment]
Hi, how is your ngx-translate configured? I did not know you could configure ngx-translate like that.

When i look at the docs i can't find it either.

**Comment by aidenwallis** [comment]
This keeps your parsed translations in the same format, binding them by language the same way, just allows for more flexible folder structures, such as my one https://github.com/aidenwallis/fossabot-translations as I opt to group by language, not module.

**Comment by larscom** [comment]
All right, seems cool to me. Will check out your PR.

**Comment by larscom** [comment]
Merged, thanks
