### ISSUE TITLE
Can we specify custom headers while loading the json from backend server

### ISSUE THREAD

**Issue by karthic-kailanware** [larscom/ngx-translate-module-loader#22]
## I'm submitting a request for how to add custom header request like passing a API key in the headers
<pre><code>
[ x] Feature request
</code></pre>
## Current behavior
Currently unable to pass custom headers

## Expected behavior
Need to pass custom Headers options
## What is the motivation / use case for changing the behavior?
We are using the Translation Management System and load the json from the server helps mutiple teams to avoid duplicate translation keys

**Comment by karthic-kailanware** [comment]
I have explored the following file, Can anyone help me to how do i implement in my project to pass custom headers
https://github.com/larscom/ngx-translate-module-loader/blob/master/projects/ngx-translate-module-loader/src/lib/module-translate-loader.ts

fetchTranslation and fetchTranslationForModule 
`return this.http.get<Translation>(path).pipe(
      map((translation) => (translateMap ? translateMap(translation) : translation)),
      this.catchError(cleanedPath, translateError)
    );`

` return this.http.get<Translation>(path).pipe(
      map((translation) => {
        return translateMap
          ? translateMap(translation)
          : disableNamespace
          ? translation
          : Object({ [namespaceKey]: translation });
      }),
      this.catchError(cleanedPath, translateError)
    );`

**Comment by larscom** [comment]
What you could do is to add an http interceptor which adds the headers before sending the request. Be sure to check the url so it doesn't get added on every request.

**Comment by larscom** [comment]
Released version **3.1.0**, you'll find it there ;-)
