### ISSUE TITLE
Build project angular v.15

### ISSUE THREAD

**Issue by SabatoRusso** [larscom/ngx-translate-module-loader#23]
When I build my angular application with this dependence, I have this warning in console:

Warning: ........../node_modules/@larscom/ngx-translate-module-loader/fesm2020/larscom-ngx-translate-module-loader.mjs depends on 'deepmerge'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by larscom** [comment]
Thanks for reporting, this should be fixed in version `3.1.1`
