### ISSUE TITLE
Using the namespace option of IModuleTranslation does not prevent namespace from being uppercased

### ISSUE THREAD

**Issue by dabbid** [larscom/ngx-translate-module-loader#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Namespace is uppercased by default, even if we declare `namespace` option in `IModuleTranslation`.

Example:
```typescript
export function translateLoaderFactory(http: HttpClient) {
  return new ModuleTranslateLoader(http, {
    modules: [{ baseTranslateUrl: './assets/i18n', moduleName: 'my-module-name', namespace: 'myModuleName' }],
  });
}

@NgModule({
  imports: [
    TranslateModule.forChild({
      defaultLanguage: 'en',
      isolate: true,
      loader: {
        provide: TranslateLoader,
        useFactory: translateLoaderFactory,
        deps: [HttpClient],
      },
    }),
```
Translation object results in: 
```
{
  "MYMODULENAME": { ... }
}
```
## Expected behavior
Declaring a namespace should bypass the default uppercase process, and so translation object should look like this:
```
{
  "myModuleName": { ... }
}
```

**Comment by larscom** [comment]
That makes sense, will update this when i can.

**Comment by larscom** [comment]
Hi, i pushed a new minor version (version: 2.1.1) that includes this fix.

**Comment by dabbid** [comment]
Hi, thank you for responsiveness!! :+1:
